version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_shoeadev
    ports:
    - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: